### ISSUE TITLE
[bug] Adding mod seems to break resource key?

### ISSUE THREAD

**Issue by Derek1256** [alec016/MMR-Energistics#1]
### issue:

Failure message: An uncaught parallel processing error has occurred.
java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:block / integrateddynamics:menril_torch]

### Mod versions:
* MMR: 1.1.7
* MMR-AE: 1.0.2
* MMR-Mek: 1.0.8
* MMR-Ars: 1.0.6
* Integrated: 1.23.19
### Steps to reproduce:
* this is a odd one, its consistent on my main pack but on a instance with just ID + MRR-Energistics it doesnt crash?
Very confused on whats it crashing on.
### Screenshots:
![Screenshot 1424  7bae11f6-c16e-4b60-a750-d35a0b500a09](https://github.com/user-attachments/assets/1208ba98-1092-4bac-baea-0bb85ddf3269)
### Logs:
* [crash-report.txt](https://github.com/user-attachments/files/17876389/crash-2024-11-22_15.03.18-fml.txt)
* [latest.log](https://github.com/user-attachments/files/17876401/latest.log)

**Comment by alec016** [comment]
i will try to fix it for the next update, i think i found the cause

**Comment by Derek1256** [comment]
👍🏼 , looking forward to the future of these mods :)

**Comment by alec016** [comment]
do you have extendedAE installed?
