### ISSUE TITLE
[Idea] ME Pattern bus & ME Extended pattern bus

### ISSUE THREAD

**Issue by Derek1256** [alec016/MMR-Energistics#3]
### The Feature:
not sure if this has been sparked before, but would be quite nice for when you have recipes that include chemicals + fluids + items all at once for whatever reason and don't wanna do some shenanigans to get it to properly work.

*if this is already added please lmk, but as far as i can tell, its not added.*

**Comment by alec016** [comment]
I have some questions:
- What is the main purpouse of those blocks?
- How they will work?
- What things they should do?

**Comment by Derek1256** [comment]
### main purpose:
skips the need to do a pattern provider on a normal input bus and or into a chest/tank, and instead can directly use patterns with the bus itself

### How will they work:
pretty much a pattern provider but in bus form.

Normal: 9 Pattern slots
Advanced: 36 pattern slots

### What things they should do:
* be able to accept processing patterns that allows for just directly autocrafting with the multiblocks.

*pretty much just a pattern buffer from GT*

**Comment by alec016** [comment]
if i understand correctly, what you mean is make a parten provider as a bus/hatch and insert the corresponding ingredients to the corresponding bus/hatch when is requested the recipe that is in the pattern provider?

**Comment by Derek1256** [comment]
correct.

**Comment by alec016** [comment]
will be nice add that, i will look into it when i finish the experience feature, im over complicating it with ae2 stuff to store the xp.
